name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  mix_check:
    name: Elixir ${{ matrix.elixir }} / OTP ${{ matrix.otp }}
    runs-on: ubuntu-24.04
    strategy:
      # Following matrix is maintained by following https://hexdocs.pm/elixir/compatibility-and-deprecations.html
      # And, only the most recent 3 versions of Elixir are involved.
      matrix:
        include:
          # Elixir v1.19
          # - { elixir: "1.19.x", otp: "28.x" }
          - { elixir: "1.19.x", otp: "27.x" }
          - { elixir: "1.19.x", otp: "26.x" }
          # Elixir v1.18
          - { elixir: "1.18.x", otp: "27.x" }
          - { elixir: "1.18.x", otp: "26.x" }
          - { elixir: "1.18.x", otp: "25.x" }
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-elixir_${{ matrix.elixir }}-otp_${{ matrix.otp }}-mix_${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-elixir_${{ matrix.elixir }}-otp_${{ matrix.otp }}-mix

      - name: Install dependencies
        run: mix deps.get

      - name: Run mix check
        run: mix check

  node_check-vite-plugin-combo:
    name: Node.js ${{ matrix.node }}
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: node-packages/vite-plugin-combo
    strategy:
      matrix:
        node: [20.x, 22.x, latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-node_${{ matrix.node }}-pnpm_${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node_${{ matrix.node }}-pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm run build
